[package]
name = "p3-lde"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = { path = "../field" }
p3-matrix = { path = "../matrix" }
p3-util = { path = "../util" }

[dev-dependencies]
criterion = "0.5"
rand = "0.8.5"
p3-mersenne-31 = { path = "../mersenne-31" }

[[bench]]
name = "mersenne31"
harness = false